api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

experimental:
  localPlugins:
    traefik-s3-plugin:
      moduleName: github.com/craigbrogle/traefik-s3-plugin
